version: '3.1'
services:
  database-manga:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'jjuser'
      MYSQL_PASSWORD: 'password-secret'
      MYSQL_ROOT_PASSWORD: 'password-secret'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: