version: '3.1'
services:
  redis-timeline:
    container_name: redis-timeline
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-volume:/data

volumes:
  redis-volume:
